spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useLegacyDatetimeCode=false&serverTimezone=UTC&allowLoadLocalInfile=true
    username: root
    password: Wisler843732
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
      # 1.use test  2.db.createUser( { user: "mongodb", pwd: "123456", roles: [ { role: "dbOwner", db: "db_name" } ]} )
      username: demo
      password: Mongo123456



